apiVersion: v1 
kind: Service
metadata:
  name: {{ include  "myapp-chart.fullname" . }}
  labels: 
    {{- include "myapp-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.port }}

  selector: 
    {{- include "myapp-chart.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}