replicaCount: 2

image:
  repository: nginx
  tag: stable

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200mi
    memory: 256Mi

nameOverride: ""
fullnameOverride: ""