frontend: 
  replicaCount: 3

  image:  
    repository: paulczar/gb-frontend
    tag: v5 
  service: 
    port: 80

  resources:
          requests:
            cpu: 100m
            memory: 100Mi
  env:
        - name: GET_HOSTS_FROM
          value: dns

backend:
  replicaCount: 2

  image:
    repository: mongo
    tag: 4.2
  service:
    port: 27017

  resources:
    requests:
      cpu: 100m
        memory: 100Mi
  args:
    - --bind_ip
    - 0.0.0.0 