apiVerson: apps/v1
kind: Deployment 
metadata:
  name: {{ include "guestbook.fullname" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}

  selector:
    matchLabels:
      labels: {{ include "guestbook.selectorLabels" . | nindent 6 }}
    
  template:
    metadata:
      labels: {{ include "guestbook.selectorLabels" . | nindent 6 }}
    spec:
      containers:
        - name: {{ include "guestbook.name" . | nindent 8 }}
          ports: {{ .Values.frontend.service.port }}
          resources:
            {{- toYaml frontend.resources . | nindent 12 }}
          env:
            {{- toYaml frontend.env . | nindent 12 }}        
