apiVersion: v1 
kind: Service
metadata:
  name: {{ include "guestbook.name" }}
  labels:
    {{ include "guestbook.labels" . | nindent 4 }}
spec:
  selector:
    {{ include "guestbook.selectorLabels" . | nindent 4 }}

  ports:
    - port: {{ .Values.backend.service.port }}