apiVersion: v1 
kind: service
metadata:
  name: {{ include "guestbook.name" }}
  labels:
    {{ include "guestbook.fullname" | nindent 4 }}
spec:
  type: LoadBalancer

  selector:
     {{ include "guestbook.selectorLabels" . | nindent 6 }}
  ports:
    - port: {{ .Values.frontend.service.port }}